# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Python\QtSkin\UiFiles\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralwidget = QtWidgets.QStackedWidget(self.widget)
        self.centralwidget.setObjectName("centralwidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.centralwidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.centralwidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.centralwidget)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_soft = QtWidgets.QAction(MainWindow)
        self.action_soft.setObjectName("action_soft")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_12)
        self.menu.addSeparator()
        self.menu.addAction(self.action_14)
        self.menu_2.addAction(self.action_10)
        self.menu_2.addAction(self.action_11)
        self.menu_3.addAction(self.action_5)
        self.menu_3.addAction(self.action_9)
        self.menu_3.addAction(self.action_6)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_soft)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Qt Skin Designer"))
        self.menu.setTitle(_translate("MainWindow", "Project"))
        self.menu_2.setTitle(_translate("MainWindow", "Edit"))
        self.menu_3.setTitle(_translate("MainWindow", "Help"))
        self.action.setText(_translate("MainWindow", "New Project"))
        self.action.setIconText(_translate("MainWindow", "New Project"))
        self.action.setStatusTip(_translate("MainWindow", "Create New Project"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_2.setText(_translate("MainWindow", "Open Project"))
        self.action_2.setStatusTip(_translate("MainWindow", "Open Exists Project"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_4.setText(_translate("MainWindow", "Save Project"))
        self.action_4.setStatusTip(_translate("MainWindow", "Save Project"))
        self.action_4.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_5.setText(_translate("MainWindow", "Website"))
        self.action_5.setStatusTip(_translate("MainWindow", "Welcome to visit http://PyQt5.com"))
        self.action_6.setText(_translate("MainWindow", "Update"))
        self.action_6.setStatusTip(_translate("MainWindow", "Check Update"))
        self.action_7.setText(_translate("MainWindow", "Faq"))
        self.action_7.setStatusTip(_translate("MainWindow", "Common problem"))
        self.action_9.setText(_translate("MainWindow", "Feedback"))
        self.action_9.setStatusTip(_translate("MainWindow", "ヾ(=ﾟ･ﾟ=)ﾉ♪Submit Feedback"))
        self.action_soft.setText(_translate("MainWindow", "About Soft"))
        self.action_soft.setStatusTip(_translate("MainWindow", "About the Software"))
        self.action_10.setText(_translate("MainWindow", "Undo"))
        self.action_10.setStatusTip(_translate("MainWindow", "Undo"))
        self.action_10.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_11.setText(_translate("MainWindow", "Redo"))
        self.action_11.setStatusTip(_translate("MainWindow", "Redo"))
        self.action_11.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_12.setText(_translate("MainWindow", "Save As Project"))
        self.action_12.setStatusTip(_translate("MainWindow", "Save As Project"))
        self.action_12.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_14.setText(_translate("MainWindow", "Exit"))
        self.action_14.setStatusTip(_translate("MainWindow", "Exit"))
        self.action_14.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

